language: objective-c
os: osx
osx_image: xcode8.3
env: TERM=dumb SHLVL=0
cache: false
git:
  submodules: true
script:
  - "( brew install libsodium json-c )"
  - "( cd ./platform-independent/cli-c && ./clean && targets='mpw mpw-bench mpw-tests' ./build && ./mpw-tests && ./mpw-cli-tests )"
  - "( cd ./gradle && ./gradlew --info clean test )"
  - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword iOS' -sdk iphonesimulator )"
  - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword macOS' )"
